# Generated by Django 5.0.14 on 2025-09-02 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name_plural': 'Service Categories'},
        ),
    ]
