# Generated by Django 5.0.14 on 2025-10-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_user_email_token_user_email_token_expires_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingSignup',
        ),
    ]
