# Generated by Django 5.0.14 on 2025-12-07 02:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_message_product_message_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/services/'),
        ),
        migrations.CreateModel(
            name='SellerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_was_deleted', models.BooleanField(default=False)),
                ('original_seller_email', models.EmailField(blank=True, max_length=254)),
                ('original_seller_name', models.CharField(blank=True, max_length=255)),
                ('reviewer_email', models.EmailField(db_index=True, max_length=254)),
                ('reviewer_name', models.CharField(blank=True, max_length=150)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_account_deleted', models.BooleanField(default=False)),
                ('original_reviewer_id', models.IntegerField(blank=True, null=True)),
                ('reviewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, limit_choices_to={'is_seller': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings_received', to='store_app.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('user_deleted', 'User Deleted'), ('reviewer_deleted', 'Reviewer Deleted')], max_length=50)),
                ('reviewer_email', models.EmailField(blank=True, max_length=254)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='store_app.sellerrating')),
            ],
        ),
        migrations.AddIndex(
            model_name='sellerrating',
            index=models.Index(fields=['seller', 'reviewer_email'], name='store_app_s_seller__09bd2c_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerrating',
            index=models.Index(fields=['seller', '-created_at'], name='store_app_s_seller__23b74a_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerrating',
            index=models.Index(fields=['reviewer_email', '-created_at'], name='store_app_s_reviewe_1fd6c4_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerrating',
            index=models.Index(fields=['original_seller_email'], name='store_app_s_origina_bdb106_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerrating',
            index=models.Index(fields=['score', 'created_at'], name='store_app_s_score_fd8064_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sellerrating',
            unique_together={('original_seller_email', 'reviewer_email')},
        ),
    ]
