# Generated by Django 5.0.14 on 2025-12-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_message_product_message_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/services/'),
        ),
    ]
