# Generated by Django 5.0.14 on 2025-12-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_alter_service_image_sellerrating_reviewauditlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewauditlog',
            name='review',
        ),
        migrations.RemoveIndex(
            model_name='sellerrating',
            name='store_app_s_seller__09bd2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='sellerrating',
            name='store_app_s_seller__23b74a_idx',
        ),
        migrations.RemoveIndex(
            model_name='sellerrating',
            name='store_app_s_reviewe_1fd6c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='sellerrating',
            name='store_app_s_origina_bdb106_idx',
        ),
        migrations.RemoveIndex(
            model_name='sellerrating',
            name='store_app_s_score_fd8064_idx',
        ),
        migrations.RemoveField(
            model_name='sellerrating',
            name='original_seller_name',
        ),
        migrations.AlterField(
            model_name='sellerrating',
            name='original_seller_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='ReviewAuditLog',
        ),
    ]
