# Generated by Django 5.0.14 on 2025-12-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_remove_reviewauditlog_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerrating',
            name='original_seller_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
