# Generated by Django 5.0.14 on 2025-12-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_sellerrating_original_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
    ]
