# Generated by Django 5.0.14 on 2025-12-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_product_sold_out_service_sold_out_and_more'),
        ('store_app', '0010_alter_userprofile_description'),
    ]

    operations = [
    ]
